name: PR Automation

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed

permissions:
  pull-requests: write
  contents: write

jobs:

  approve:
    name: Auto approve PR
    if: |
      github.event.action != 'closed' &&
      github.event.pull_request.mergeable == true

    runs-on: ubuntu-latest

    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge \
            "${{ github.event.pull_request.number }}" \
            --repo "${{ github.repository }}" \
            --merge \
            --auto


  sync:
    name: Sync deployment fork
    if: |
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: PR was merged
        run: |
          echo "PR #${{ github.event.pull_request.number }} was merged."
          echo "Sync deployment fork here."
